services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: YOUR_USER
      POSTGRES_PASSWORD: YOUR_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data: